name: Releases

on: 
  push:
    branches: [ main ]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate tar archive
      run: ./generate-tar.sh ${GITHUB_REF##*/}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "openwrt-tailscale-enabler-*.tar.gz"
#         bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
